version: "3"
services:
  server:
    build: server/
    command: go run server.go
    ports:
      - 4040:4040
  client:
    build: client/
    command: go run client.go
    network_mode: host
    depends_on:
      - server